backend:
  name: github
  repo: nicholasnasc/paptools
  branch: main

local_backend: true

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Título
        name: title
        widget: string
      - label: Autores
        name: authors
        widget: list
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Data
        name: date
        widget: datetime
      - label: Imagem
        name: image
        widget: image
        required: false
      - label: Conteúdo
        name: body
        widget: markdown

  - name: docs
    label: Documentação
    folder: docs
    create: true
    fields:
      - label: Título
        name: title
        widget: string
      - label: Sidebar Position
        name: sidebar_position
        widget: number
        required: false
      - label: Conteúdo
        name: body
        widget: markdown
